### ISSUE TITLE
Error using variables to name note

### ISSUE THREAD

**Issue by BananasAreGoodForYou** [sundevista/youtube-template#10]
I am attempting to automatically name my note based on variables.
I want the note created in the vault root with the name to be "{{channelName}} - {{title}}.md"
To accomplish that I am assuming I need to turn on "Use path template".
Below I fill in "Path Template". I attempt this using:
{{channelName}} - {{title}}.md
temp/{{channelName}} - {{title}}.md (creates the folder then errors)
{{channelName}}.md

Unexpected error: File ' ' does not exist

I feel like I am missing some syntax error right in front of my face. Thanks for any help and the plugin is dope.

**Comment by BananasAreGoodForYou** [comment]
I just had to post for help. 
The use template file was still accidentally on.

**Comment by sundevista** [comment]
@jtwilkins Then, as I understand, issue is resolved?

**Comment by BananasAreGoodForYou** [comment]
Yes, user error has been resolved.
