### ISSUE TITLE
Sanitizing {{title}} for valid filenames

### ISSUE THREAD

**Issue by p33k** [sundevista/youtube-template#13]
Some videos use titles with | or [] or # or ^ which can cause problems (at least according to the error message):

![illegal characters](https://github.com/sundevista/youtube-template/assets/6191925/34018982-0c33-4b5f-b958-399162dd1904)

**Comment by p33k** [comment]
could be rather easy be done in the youtube.ts with adding a function (depending on what characters should be removed):
`function sanitizeTitle(title: string): string {
    return title.replace(/[\/:*?"<>|#^\[\]]/g, '');
}
`

and cleaning the title below: 
`title: sanitizeTitle(filterStringData(videoResponse.items[0].snippet.title)), `

**Comment by sundevista** [comment]
Fixed in the latest version
