### ISSUE TITLE
Customization of {{noteCreated}}

### ISSUE THREAD

**Issue by p33k** [sundevista/youtube-template#14]
when I set the Path template to : Resources/YouTube/{{channelName}}/{{noteCreated}} {{title}}.md

the Filename looks like this: "2024-05-18, 1121 Video Title XYZ" is there a way to get rid of the (strangely formatted) time?

**Comment by p33k** [comment]
changed it as a hotfix for me in the youtube.ts like this: `noteCreated: moment().format('YYYY-MM-DD'),`

**Comment by sundevista** [comment]
Yes, it's strange that I've added "HH:mm" to format, I'll fix this

**Comment by sundevista** [comment]
Fixed in latest version
