### ISSUE TITLE
Failed to Install Plugin

### ISSUE THREAD

**Issue by rfdiazpr** [sundevista/youtube-template#15]
18MAY24 Tried to install the plugin and it is not working
![image](https://github.com/sundevista/youtube-template/assets/707196/01d136f8-5755-454b-b18c-e955b3aab253)

Also tried to apply the update on another vault with a prior and working installation, and it does not work.

**Comment by sundevista** [comment]
@rfdiazpr It was failing due to the wrong release structure, now it's fixed. Thanks for catching!
