### ISSUE TITLE
Unexpected error: Attachment folder './attachments' does not exist

### ISSUE THREAD

**Issue by palwoo** [sundevista/youtube-template#3]
I installed [1.0.7](https://github.com/sundevista/youtube-template/releases/tag/1.0.7), it said :"Unexpected error: Attachment folder './attachments' does not exist"

**Comment by sundevista** [comment]
Hello, @palwoo! Can you please share the settings for your attachments folder in Obsidian Settings → Files and links → Default location for new attachments and Attachment folder path.

**Comment by palwoo** [comment]
Thank you，@sundevista 。
<img width="565" alt="Snipaste_2024-01-30_17-18-31attacnments" src="https://github.com/sundevista/youtube-template/assets/83803265/be63d53c-83f5-498b-8106-746c96a64272">

I tested again，then another message appeared: "Unexpected error: Cannot read properties of undefined (reading 'url')", but YouTube Data API v3 received those requests
<img width="591" alt="Snipaste_2024-01-30_17-11-09youtube data api" src="https://github.com/sundevista/youtube-template/assets/83803265/2bb13b3b-a215-4353-9a85-3f4888f234bf">

**Comment by sundevista** [comment]
Can you please share the URL you've used and console output during this operation from Obsidian Developer Tools? (Option + Command + I for Mac and Shift + Ctrl + I for Windows)

**Comment by palwoo** [comment]
Perhaps those errors were caused by other things.  I will check them later. I built a new vault and this time your plugin works very well.  Thanks again.

**Comment by sundevista** [comment]
I will not close the issue for now. If you discover what is causing the plugin to malfunction, please let me know. I will attempt to find a workaround for this error.

**Comment by palwoo** [comment]
1. ![Snipaste_2024-01-30_21-07-29](https://github.com/sundevista/youtube-template/assets/83803265/5bfa759e-a747-4b0f-9e87-6f85a0c88b0d)

2. [obsidian.md-1706619802719.log](https://github.com/sundevista/youtube-template/files/14098280/obsidian.md-1706619802719.log)

3. ![Snipaste_2024-01-30_21-09-02-second](https://github.com/sundevista/youtube-template/assets/83803265/3408bc84-a933-4e1d-af57-8e82d1c9f654)

4.  When your plugin say "Unexpected error: Attachment folder './' does not exist", there is no new log in console

**Comment by sundevista** [comment]
@palwoo should work fine after the last release (1.0.8). Please update the plugin and let me know if it works.

**Comment by palwoo** [comment]
[[BUG] TypeError: Cannot read properties of undefined (reading 'editor') · Issue #503 · vslinko/obsidian-outliner](https://github.com/vslinko/obsidian-outliner/issues/503), I disabled it temporarily. I updated your plugin, but the error is same.

<img width="783" alt="Snipaste_2024-01-31_08-19-32youtube" src="https://github.com/sundevista/youtube-template/assets/83803265/03f77b44-959a-4864-95ab-7c97b1efaca2">

<img width="404" alt="Snipaste_2024-01-31_08-35-06" src="https://github.com/sundevista/youtube-template/assets/83803265/3a93d612-6a1a-4b6f-9364-afbb6b9cd631">

**Comment by sundevista** [comment]
@palwoo It seems I understand your concrete issue now. You're using the "In the subfolder under the current folder" option for the "Default location for new attachments". So, if this particular subfolder doesn't exist, the plugin will not create it itself (because I don't want it to perform any folder creation actions, as it may lead to mess and unexpected results for the user). Therefore, you need to change the option for "Default location for new attachments" to "In the folder specified below" and choose the appropriate existing folder.

But if you really need this particular workaround with a subfolder, let me know, and I'll add a special option to unset folder creation restrictions.

**Comment by sundevista** [comment]
Hello, @palwoo! Have you tried using option "In the folder specified below" with existing folder?

**Comment by palwoo** [comment]
@sundevista Thanks, I tried using option "In the folder specified below" with existing folder and it succeed.

**Comment by sundevista** [comment]
Okay, then I'm closing the issue. Feel free to create another one if you find something strange.

Thanks!

**Comment by neowukong** [comment]
麻烦添加对 在当前文件夹下的子文件夹中 的支持，不然缩率图下载的功能可能没法用
