### ISSUE TITLE
Ability to customize YouTube note title

### ISSUE THREAD

**Issue by NobleUplift** [sundevista/youtube-template#4]
Just like Book Search: https://github.com/anpigon/obsidian-book-search-plugin

Would it be possible to customize the title of each Note? Something like {{title}} - {{channel}} or {{channel}} - {{title}}?

**Comment by sundevista** [comment]
Nice idea! It will be implemented in the next release.

**Comment by sundevista** [comment]
Please, update to 1.1.0. Your request should be resolved
