### ISSUE TITLE
Make downloading thumbnail optional/second command

### ISSUE THREAD

**Issue by NobleUplift** [sundevista/youtube-template#5]
Not sure which would be easier, but could there be an option to download/not download thumbnails, or a command for "YouTube Template: Insert template" or "YouTube Template: Insert template with thumbnail"? I don't want to clutter my repo with YT thumbnails. I also use Obsidian Sync and I'm sure this would slow down the sync if scaled up.

**Comment by sundevista** [comment]
Hello, @NobleUplift! If you don't include `{{thumbnail}}` in your template, it won't be downloaded. This option has been considered. I will add a text notation about it in the plugin settings.
