### ISSUE TITLE
Unexpected error: Attachment folder './attachments' does not exist

### ISSUE THREAD

**Issue by rsinitsin** [sundevista/youtube-template#7]
Hello there. 
I've got a subj error on the insert template pop-up window. 
I'm saving attachments in the subfolders under the current folder. Looks like your template trying to use the relative path "./attachments". Could it be possible to use an absolute path for the files directory like "vault_name/folder/attachments"?

**Comment by sundevista** [comment]
Hi @rsinitsin! This is a known issue that will be fixed in the next release. Currently, the plugin uses the attachment folder from Obsidian settings without additional path normalization.

**Comment by sundevista** [comment]
Please, update to 1.1.0. Your request should be resolved
